In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X = iris.data

In [7]:
y = iris.target

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [10]:
y = to_categorical(y)

In [11]:
y.shape

(150, 3)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.33)

In [14]:
from sklearn.preprocessing import MinMaxScaler # minmaxscaler is the range value of 0 to 1

In [15]:
#np.array([50,100,150,200])/20

In [16]:
scaler_object = MinMaxScaler()

In [17]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [18]:
scaled_X_train = scaler_object.transform(X_train)

In [19]:
scaled_X_test = scaler_object.transform(X_test)

In [20]:
from keras.models import Sequential
from keras.layers import Dense

In [21]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [22]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [32]:
model.fit(scaled_X_train,y_train,epochs=150,verbose=2) #epoch is input,verbose is output information

Epoch 1/150
 - 0s - loss: 0.7773 - accuracy: 0.6700
Epoch 2/150
 - 0s - loss: 0.7679 - accuracy: 0.6900
Epoch 3/150
 - 0s - loss: 0.7578 - accuracy: 0.6900
Epoch 4/150
 - 0s - loss: 0.7486 - accuracy: 0.6700
Epoch 5/150
 - 0s - loss: 0.7396 - accuracy: 0.6600
Epoch 6/150
 - 0s - loss: 0.7307 - accuracy: 0.6500
Epoch 7/150
 - 0s - loss: 0.7216 - accuracy: 0.6500
Epoch 8/150
 - 0s - loss: 0.7130 - accuracy: 0.6600
Epoch 9/150
 - 0s - loss: 0.7046 - accuracy: 0.6800
Epoch 10/150
 - 0s - loss: 0.6958 - accuracy: 0.6800
Epoch 11/150
 - 0s - loss: 0.6873 - accuracy: 0.6700
Epoch 12/150
 - 0s - loss: 0.6791 - accuracy: 0.6600
Epoch 13/150
 - 0s - loss: 0.6717 - accuracy: 0.6500
Epoch 14/150
 - 0s - loss: 0.6642 - accuracy: 0.6500
Epoch 15/150
 - 0s - loss: 0.6566 - accuracy: 0.6500
Epoch 16/150
 - 0s - loss: 0.6493 - accuracy: 0.6700
Epoch 17/150
 - 0s - loss: 0.6423 - accuracy: 0.6800
Epoch 18/150
 - 0s - loss: 0.6355 - accuracy: 0.6900
Epoch 19/150
 - 0s - loss: 0.6288 - accuracy: 0.6900
Ep

In [33]:
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)

In [34]:
predictions = model.predict_classes(scaled_X_test)

In [35]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [36]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [37]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]], dtype=int64)

In [38]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [39]:
accuracy_score(y_test.argmax(axis=1),predictions)

0.96

In [40]:
model.save('myfirstmodel.h5')

In [42]:
from keras.models import load_model

In [43]:
new_model = load_model('myfirstmodel.h5')

In [45]:
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)