In [1]:
import pandas as pd

In [2]:
npr = pd.read_csv('npr.csv')

In [3]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [4]:
npr['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [5]:
len(npr)

11992

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
cv = CountVectorizer(max_df=0.9,min_df=2,stop_words='english')

In [8]:
dtm = cv.fit_transform(npr['Article'])

In [9]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.decomposition  import LatentDirichletAllocation

In [ ]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [30]:
LDA.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [25]:
# Grab the vacabulary of words

In [26]:
len(cv.get_feature_names())

54777

In [27]:
type(cv.get_feature_names())

list

In [28]:
cv.get_feature_names()[4000]

'atizado'

In [29]:
import random
random_word_id = random.randint(0,54777)
cv.get_feature_names()[random_word_id]

'multidisciplinary'

In [31]:
# Grab the topics

In [33]:
len(LDA.components_)

7

In [34]:
type(LDA.components_)

numpy.ndarray

In [35]:
LDA.components_.shape

(7, 54777)

In [36]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [38]:
single_topic = LDA.components_[0]

In [39]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [41]:
import numpy as np

In [43]:
arr = np.array([10,200,1])

In [44]:
arr

array([ 10, 200,   1])

In [45]:
arr.argsort()

array([2, 0, 1], dtype=int64)

In [47]:
single_topic.argsort()[-10:]#Last 10 values of arg sort

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [48]:
top_ten_words = single_topic.argsort()[10:]

In [ ]:
for index in top_ten_words:
    print(cv.get_feature_names()[index])

hajime
ecstatically
granduciel
erivo
thugger
hight
jewly
gruffly
chinen
millenniums
xxl
ennio
morricone
birchard
astrobiological
mccool
wieman
remixers
charly
unsettlingly
gimlet
masterworks
archly
sunniness
idk
bares
jp
tipton
masonic
bathgate
cu
thielen
sza
quark
astrobiology
chard
empirically
bergson
oracular
carjacking
ewf
misfolding
superpowered
granularity
kenema
algebraic
nigatu
cjd
anthropocene
allspice
lungi
posnanski
ramone
jamila
ledisi
revivalism
cytoplasm
andris
dejohnette
luen
cubed
barnbrook
dependably
mobley
analytic
jammy
overproduced
tbis
radiolab
cantus
bray
epigenomic
stelling
delago
fenugreek
supplementation
heben
relativity
etu
aggravates
pipette
llorenti
quippy
childress
quarks
bootcamp
smolin
scialfa
mehldau
soundcheck
greil
undark
dougherty
selingo
unsalted
cresent
xxxtentacion
saroo
ceaselessly
habitability
electromagnetism
atone
arkestra
rinsed
heteronormative
granulated
sparklingly
downballot
ennobling
estrangement
kabocha
grandmasters
wbgo
weems
masto
haha


judas
elverum
baseballs
inconceivably
themyscira
bahia
supermassive
madmen
humors
crawfish
ancestries
yeltsin
roly
spacewalks
haibatullah
tlop
biryani
bologna
homme
rtbf
albers
oboe
corseted
baccarin
morena
briny
neve
saviour
urbane
nitze
alnwick
gaslight
sass
chickenpox
broiling
farmville
saakashvili
firebomb
dilate
prude
esl
countercharges
sugata
jadavpur
skimping
chordal
hadza
mullah
garbled
zendaya
sarin
walkin
virtuosos
liron
tair
tagel
prospero
pathos
shlockmeister
lohaus
unaddressed
mournfulness
surveilled
hocks
comets
alloys
saydnaya
roussos
hadreas
leavin
schlack
misbehave
aufschrei
transference
vestigial
crema
bonhoeffer
neetu
soju
uggams
gossett
decathlete
hpsci
prussian
yeun
flinched
nonsteroidal
hannigan
enten
penzance
bespoke
lamentations
bessie
uncivil
heiko
collude
grungy
habilis
parnes
jiggly
io
undertaker
watford
subhead
katzif
andouille
triplicate
vrt
dessner
demme
bioengineer
automatons
satiety
electro
chanterelles
busta
baskervilles
flukes
grasse
longwood
northumbe

712
magdalene
pansy
glares
schuyler
panache
empress
unredacted
desiigner
anvil
shortcake
iberian
agriculturist
atmospherics
dateline
huntress
explorations
arterial
dozed
lunges
ravishing
akira
outcropping
spearphishing
fairport
solider
bfg
iannucci
jell
aaldef
splc
timo
messiness
beemsterboer
armload
fanclub
boleyn
jotted
erectus
trumpertantrum
pulsating
skottie
mosh
058
geez
plausibility
inbreeding
objectifying
thrusters
sorrentino
dissonant
sonata
ricochets
stepdad
theron
multistory
americorps
goldstone
myrddin
entropy
tinier
classicist
transvestite
breathy
badu
mayday
unearths
vershbow
partaking
entrenches
generalists
staccato
recombination
mantises
nalgene
elsamarie
mcclellan
crotches
serialized
dicamillo
gawky
intimation
rictus
billowy
ingmar
cob
stylings
dilly
dally
shakya
callander
triathlons
felice
brontes
taskmaster
saffie
accentuate
tavitha
moorer
siccing
fairground
snaky
gorbachev
geneticists
turpentine
zabi
recanting
masekela
arachnids
annexing
raymie
scallops
perm
bosma
br

uncensored
pelvises
bossy
ouroboros
handlebars
halperin
griner
16mm
mystics
stabs
ranted
pratfalls
somethin
godrich
inborn
prideful
tuareg
mathias
zamarripa
eulogizing
gis
castner
walloping
peart
enchant
linklater
kilotons
lettenberger
folky
vaudeville
lev
roeg
newsy
icecaps
tasmania
bubonic
antwerp
jello
tywanza
gamelan
esso
sylvan
documentarian
unashamed
staining
creepier
sparhawk
vidya
maronite
beirutis
fakher
leil
massad
bersani
salit
hyphen
disenchanted
asphyxiated
kathrada
ummah
leaderboard
armenians
callum
borchers
prehistory
shrieked
bewitching
jordana
hochman
nematodes
gladwell
cityscapes
fistfuls
sputter
dorman
macdougall
roughneck
blisteringly
angelic
lucien
compositional
lunged
backstabbing
dementing
reek
unreservedly
omniscient
ejaculation
trodden
liston
quintin
offbeat
dilla
lindner
lefebvre
esmail
newsham
pizzagate
josey
zobrist
namaste
wistfulness
indoctrinating
tadpoles
winnow
shriver
finessed
jollof
739
zeit
jarosz
phallus
pangs
tresses
phylum
preciousness
warmhearted

rhapsodizing
toucan
billowing
islamism
disassembled
bonnaroo
rubenstein
kony
enfranchised
coastguard
thumping
cleary
descartes
arianne
obi
ainsley
lads
smidge
intuitions
neuron
fatma
saucer
avalon
rooming
appeasing
ipswich
karena
dejesus
wally
goebbels
neko
bolero
elana
expound
scheer
indescribable
papazian
blasé
benoit
wrongness
slinky
hyenas
mediocrity
nips
sameness
salve
humanized
noncomplementary
thuds
dotson
mistreat
reassigning
curley
bangla
precept
dopey
spewed
brittney
fizzes
honeyed
ladybug
quintero
gramophones
limped
evolutionarily
stripey
975
tov
mazel
fluffysharp
shabazz
hansard
naughten
gloppy
hana
christensen
riverine
benefitted
tasmanian
soni
tomcat
bartoli
trinidadian
vo
neurobiological
irresistibly
intoxicant
hamed
omens
rocketing
gerri
sloppiness
marketti
turd
orphanages
dunbar
tanja
roes
ginsberg
baggier
agitates
lubricates
angling
ultraviolet
blobs
moons
abode
yevgeny
sunlit
guillory
vvd
appended
annadurai
vellum
jemima
contorts
moustafa
likeability
hadfield
ridgewo

squirms
ahmadi
nuremberg
radiates
shreds
1840
conjectured
reappearing
sharecroppers
giroux
executioner
lilacs
seratones
dagger
aviator
disenfranchises
vaccinators
eisenman
unresisting
embankment
nyquist
winged
docility
atrocity
conditioned
castigates
bullfighting
conversationalists
tedeschi
iskander
mannan
overcaffeinated
dreamier
yan
bordelon
overpowering
tolkien
scavenger
sludgy
tbi
suffocating
tether
mollusks
vh1
abaaoud
natalia
sprinted
abdelhamid
neem
weightlifter
archeologists
handcuff
adulation
maayan
astrobiologist
earphones
idling
righteously
sinuous
blotchy
beacons
bloodstained
prostrating
centerfield
calibre
coulton
bock
hearkens
dolce
hazed
instinctive
statesmen
starling
razors
excelling
farrar
rekindle
ogle
tayeb
489
branching
catafalque
bagpipe
jorts
gumpangkum
sire
terrestrial
amanar
volunteerism
cregg
typeface
maitre
kristan
softness
malakagharib
bouncy
nefertiti
pagoda
coaxing
wyncote
salha
leaping
privation
volts
birdsong
gwangwa
abounded
matriarchs
orangeburg
alvanoe

morgenstern
kipling
burkas
invertebrates
indulgences
elongating
oddisee
torrid
esmé
subatomic
caja
carin
ac
japandroids
merrimack
unspeakably
tacs
transmitters
liza
auditory
whodunit
cornelius
khuram
absolution
batygin
duchovny
tarantino
jagannath
metabolizing
shred
sorcery
distended
peshawar
filaments
talley
rollercoaster
repudiated
incorrigible
steinhauser
lyn
fawcett
hewed
amphibian
individualistic
desensitized
puccini
outmaneuver
tantrums
nanometers
santería
edamame
fellini
stereos
yoon
peekaboo
muflahi
benched
markman
peep
animalistic
beenish
mcsubface
naveira
garabato
subby
vexes
lobes
wobbles
starbard
famer
larynx
nonliving
aliya
gamma
bookend
deviled
dane
cyborgian
dmc
donoghue
toothy
tselem
zambelich
kipnis
nightstand
macguffin
joao
bicep
greenies
viz
raconteurs
poof
chokeholds
undertone
elisha
lila
nueces
shroud
nast
mizoguchi
rashomon
castrating
67th
kirtland
unbounded
obscura
jasons
finkbeiner
sunscreen
geiger
koala
imaginatively
wreaks
polemic
lianna
headers
rhaina
whackin

prototypical
petals
deletions
cohere
cobras
seddique
semifinals
wrangler
pistorius
archness
detonators
thrasher
scoreless
interconnectedness
hanky
panky
glossary
perceiving
hooker
amie
rbg
corns
excommunicated
wahpeton
wim
approximation
obeys
gunfights
bashi
sinners
rpm
longhorns
ppis
zirkle
tint
scowling
distressingly
shearwater
schwa
ppi
reaper
nidal
qian
ribald
pantomime
tectonics
goddammit
cobwebs
riskiest
reimagine
vaporized
bystrom
stolid
intensities
dzhokhar
bardem
babson
bea
insitute
cortical
kraftwerk
hyphenated
devito
hoagy
trimmer
fossilization
charlap
sidemen
acquit
brainfeeder
kohlhepp
alexandros
rama
brightening
graeme
streaking
worldbuilding
entrancing
kazin
tamika
darlington
bas
granta
catchings
garbus
monoculture
repentance
xenon
wilds
theatlantic
fainting
recalibrated
conceives
lourd
supercharged
deconstruction
demigod
astrologer
softens
thoroughgoing
gendarmes
theoreticians
khateeb
gunny
magnifying
submersibles
cts
vertiginous
timbaland
lionizing
locke
loftier
neuter

wisecracking
bamberg
terrains
repose
southampton
odessa
radicalizing
scummy
leaden
cowards
prri
iceman
alcatraz
cheetah
talcum
switchbacks
broody
newsmen
upstanders
braggadocious
apatow
underpins
rocksteady
arevalo
masterchef
slobogin
gitler
backhand
retaliations
musas
hooligan
ganged
dehumanization
wexler
melodramatic
reassign
trivialized
mothership
clarice
haidar
loggins
hamda
bracketed
unsinkable
jolting
jalapeños
suki
cloned
cava
penitence
subjugated
bari
rodrique
viking
covet
nimrud
sian
drunker
negotiable
dainty
tcm
elsa
traversed
janofsky
banderas
parables
parkas
yazidis
stupendously
barbadian
bugle
rounder
lvl
oc
crumbles
loners
nineveh
evancho
thorsten
ohsu
dishonors
plumage
reexamined
substrate
locascio
ordination
sensuality
supposition
mmm
abides
neocons
invigorated
sputtered
ronni
reliefs
molins
duffel
1820
rakeyia
disillusionment
ivanovich
cortex
instigators
ladles
coarser
cohesiveness
kundun
sudeikis
rtj3
mcinerny
albanian
sarajevo
secretions
concisely
passively
gna
durum

antihero
edgier
ignition
moulton
electrons
frazzled
coolers
humayun
pullover
subtraction
didactic
klan
figurine
inhibits
bunches
blackstar
multiracial
plume
nipple
liqueur
genderqueer
hanlon
wakame
rickman
dorito
grinch
rebutting
genomes
tableau
antifungal
klux
kepler
quinto
amri
pagan
whomp
appreciations
echelon
clemson
concomitant
deify
bangers
roxy
cymone
thinkpiece
nonconformist
fantasizing
brookshire
überfunky
prophecies
prefigured
tomes
devo
thumper
garlicky
33rd
katchow
macklemore
wallpaper
haricots
puny
brassy
dimitrios
blyton
chicano
miming
cannily
bolshevik
pez
pta
soundscapes
neuroscientist
naturalistic
squirrels
premiering
clinch
nagasaki
indulgent
colloquial
ventimiglia
eels
reville
inventiveness
glorify
prendergast
lochte
coronal
wtf
dearest
leitch
erotic
felicity
unapologetically
rapunzel
erotica
engrossing
elemental
niles
neller
saidah
alyn
adelaide
dachshund
bedside
maxson
extrinsic
gradebook
willett
tahini
scold
foreword
maelbeek
retort
conaway
melodic
daze
1850
spenc

lifeguard
wwii
pert
endgame
indulging
millstone
operandi
slyly
jaimie
masons
mannered
intuition
cathryn
barbecues
postmodern
noelia
spotters
higgs
geophysicists
ewes
suitors
sars
knope
resonances
electable
radicalism
cte
simmonds
rami
seminole
efe
quip
swarms
moby
northerners
necrotizing
savvily
patrik
lackadaisically
homecoming
incitement
ryuichi
cassettes
norwich
murres
gibran
commuted
triglycerides
dalal
ayman
ironing
sneering
mio
kooky
bardo
ria
imperator
gloriously
cruelest
addams
dian
fictionalized
partied
artistes
bodysuit
googled
kurtulmus
graveyards
genera
lengthwise
folkloric
romanticism
shimmying
idiosyncratic
tengo
conor
grammatical
tahiti
mashes
crepes
mitsuha
vivian
hotshot
penultimate
schoolroom
snipes
rubbery
milky
pallidum
tamim
shaquille
lamenting
superbowlhaiku
rachael
hamad
kaliningrad
nobly
booky
shadi
sakharov
evicting
merrily
hatcher
corroboration
1864
bamako
postures
pelican
abscess
dente
mulaney
tig
reitze
attaran
storyteller
reverend
michaux
cong
squirts
subti

letterpress
skewer
outcasts
schoolmates
germane
1810
portly
wordy
chink
lithuanian
foothill
operable
saliva
coupledom
romances
neale
exclaiming
alda
mausi
niki
spruce
hurston
underrecognized
exposé
fumbling
masterminds
lizzie
grammarians
proscribed
eons
reversion
shrek
bouie
fowls
bowditch
mazen
scrawl
astroturfing
flask
swingers
figurative
supercomputer
choirs
gecko
pkk
relaxes
deus
prewitt
milliseconds
marlon
scampering
cyberthreats
tamarind
stopwatch
sonali
milliliter
havisham
cardamom
poc
blitzer
downton
reassuringly
immunized
cryptosporidium
shigella
gaudy
alford
intersectional
amazes
stomps
wavy
curmudgeon
ryerson
sos
revulsion
beckman
prejudiced
unnervingly
fairytale
pathogen
remarry
malfunctioned
guiltily
tradecraft
wattle
tituss
crumb
kwanzaa
motherly
rosalind
lynched
radicalization
deliciously
jonson
unruh
brinkley
handstands
amaranth
blogged
realms
shipp
catwoman
conscripts
liminal
sakamoto
algebra
pachinko
misfired
compasses
zaida
firefly
coppola
harding
stomping
liaisons
m

chaat
ramadurai
charukesi
napoleonic
guyana
brenton
absurdist
alec
rakim
kos
dissects
virgins
cheesecake
fatima
reopens
screenwriter
irna
magnum
unadorned
durant
furry
folic
systolic
fistfights
aftertaste
burka
penitents
konstantin
forager
embryos
cantaloupe
furrow
ferret
panhandlers
criminalization
domestication
fawn
handshakes
negga
plantains
lao
recast
screwball
dismaying
cocked
jessa
scoped
lightbulb
kazan
serendipity
banished
biopics
caramel
stanch
cowardly
cannonballs
hypothesis
expressiveness
muso
discourses
vadas
lorenz
fallujah
stews
gulp
loaf
pryor
medvedev
overflowed
audiobook
identifications
houthis
biggie
erez
judah
chp
redesigning
harmer
haelle
morel
cavuto
nuclei
imprinted
conan
tarantella
crosby
paho
understudied
finisher
punk
jimi
def
vegetative
afterword
onscreen
anarchic
handfuls
mixtures
illustrator
rapprochement
testosterone
mouthpiece
dervish
manhood
kurdish
phr
epithelium
derivatives
gaol
nonconforming
geologic
juleps
pretentious
microorganisms
interstellar
mahog

violencia
mapa
cuccinelli
monkees
nihilistic
concision
irritants
yglesias
quintet
smokies
statesmanlike
purples
charade
denzel
evangelical
vegetarianism
reruns
gazprom
winfrey
4x100
bioengineering
gogh
pocs
guffman
amiable
banal
critters
unvaccinated
linka
merch
bolduc
avalanche
canola
666
assimilated
tase
akyol
spines
abdallah
burglars
unorganized
sedative
comrades
deftly
directorate
glsen
victorians
thousandth
relativistic
daines
trapper
finalist
diffidence
globes
lapis
viva
valeria
fission
unimportant
ornament
monell
creak
bartok
picturing
griffiths
bores
retractable
entrekin
naled
pseudomonas
dullish
lager
haiku
microcephalic
whitford
origami
sycophants
tenured
schlein
tatters
fiendishly
senatorial
volcano
christa
anyways
fisc
colson
savory
bautista
noncombat
mermaid
imparts
conservationist
flirtatious
fibrous
goldfish
dissident
acorn
virginity
republicanism
prose
catskill
buddha
girding
naught
spittle
arborist
lumpectomy
pendennis
bomber
lumpy
pacino
sparingly
trusty
preaching
sna

calluses
lupita
desiccated
recreated
nests
korematsu
vanities
royally
hurried
emigrated
slaughterhouse
grouchy
shantytowns
proudest
indignities
condemns
rationally
dissension
serviceman
pesquet
sicily
blackmun
suffragists
fisa
rapacious
parisian
splayed
elmore
dangling
extraterrestrials
capitulate
dissection
seahorses
extermination
chimeras
cuffs
diggs
aztec
disavows
ultrasounds
bile
feist
guitarist
paperbacks
slyness
electing
tambacounda
elitists
speechmaking
drawbridge
guggenheim
casein
dramedy
eternally
artifact
countering
intrinsic
weirdo
infecting
crisp
dredged
rancor
chili
pursing
culpable
gerwig
cauldron
shag
irredeemable
whaler
repressed
misogyny
overexposed
sobbed
exacts
haplessly
pint
opal
dyslexia
hovercraft
achievers
manganese
falcons
simulating
undeservedly
deconstruct
zionist
voss
potted
eaters
daqneesh
sane
tropes
theses
crumbs
baggy
thickened
biogas
pernicious
particle
laotians
fluff
infiltrators
gratin
mercenary
00s
mycobacterium
mcdermott
bermudez
balmy
mani
screenpla

mucous
manny
bassist
sensed
mice
jodhpur
fgm
statuette
mercilessly
reindeer
femmes
penguin
geoscience
vowels
fairvote
kaling
defensiveness
talia
rutted
overdiagnosed
refraction
bambi
fatimah
syriac
jacksons
discoverers
hrw
reggae
transmuting
hayley
sadist
chefs
hypoglycemia
northup
hue
bridesmaids
clutch
falk
hooligans
hd
maus
miraculous
habitually
sarmiento
interdimensional
1865
brody
diatribes
pedicure
akimbo
tabasco
hon
obscenity
montages
astounded
getaways
asymptomatic
386
boorish
strangeness
persona
mozart
mercifully
aguilera
torment
reissues
biopsy
algerian
buoyant
playhouse
berth
placard
gerhard
cafés
pierced
dobson
slippers
afresh
tragicomic
locavore
cloaked
gatefold
kellymcevers
nprembedded
urinal
mccurdy
eggcup
cale
ivy
deinstitutionalization
autobiographical
masterstroke
phobia
viticulture
sochi
crusts
attests
constantine
furs
feathers
geezer
perihelion
lawbreaker
fists
chaupadi
appealingly
interface
closeups
mussels
ding
conners
macron
catt
articulation
veloso
captivating
r

salient
prods
moveon
conquistadors
hajdu
umbilical
unkind
jericho
gregor
roxham
swaziland
cicadas
spy
a320
ruppert
rasha
adventurers
diphtheria
sorties
photoshop
stamper
electrocardiogram
warships
galicia
hatred
jabber
kamran
blunter
fingertips
forsaken
conceptually
overalls
coincidences
infallible
haynes
boa
sarhaddi
saigon
freetown
stew
christianity
intermediary
tugging
dispassionately
twilight
juilliard
taut
demagogue
appendectomies
curriculum
kabul
altruism
doughnuts
stardom
broth
ang
cultured
dont
upadhyay
genus
owl
melville
gasped
carrington
ballistic
cloture
tha
cataloging
ol
ravenous
polo
monika
aubergine
ageing
virtuoso
platelets
tropics
vulgarity
thierry
melodious
acidic
sassy
zooplankton
excursions
wiretaps
boxful
akai
crenshaw
armory
nothingness
crème
inhibition
harward
chipper
undertreated
disenfranchise
evoke
briefings
rescuer
technicolor
commandeered
vinci
folger
abdomens
eternity
essayists
coens
dimpled
sudamericana
archer
pong
strums
axis
falsifications
karma
bubbling


cate
teleprompter
weariness
slices
dias
bombers
1300
samoa
nomadic
earthen
bassinet
doubtless
hardhat
basmati
pompeo
subjugating
helmets
horticultural
pesto
unloved
vaccination
singsong
oswald
whiskey
interminable
existences
comey
amputations
punchy
heave
religiosity
puncture
scab
galleries
bento
lofts
turkmenistan
dante
ahem
seditious
difranco
grandin
poisonous
overcompensate
vegetation
disavowed
patio
scalps
unspoken
darkened
moroccan
infants
unnatural
christened
shae
soaking
clarence
missiles
insides
picaresque
reinterpret
wham
slopes
nosratollah
khosravi
imagining
bopping
yapping
plums
cabral
rabid
preordained
ramblin
determinants
barlow
spandex
dizziness
katyal
stalks
disco
beetles
sepulvado
samoas
agostino
climbers
hopeless
dellinger
shawnee
retested
pickles
obscenities
obliges
dreamy
wobbled
estonia
isa
glimmers
parlors
norris
beardsley
hpv
tinkerers
henan
smothering
tejano
candelabra
wiggly
caucuses
plantings
cuyes
archaeological
steinem
gunship
vizier
ogled
steelers
dishing
pa

unworthy
nodapl
plague
apocryphal
extinctions
groundless
breaths
niqab
mccarthyism
filet
pentecostal
knob
artwork
entertains
nomad
snobs
females
feral
lowland
insect
sensitivities
virtuosity
endorser
fanbase
abcs
careerwise
amends
limon
hatchlings
sushi
fives
fairmont
abdo
indestructible
documentaries
howie
hardscrabble
uninjured
delicacies
tacky
idolize
ame
bridgegate
pyres
reedy
numbing
gatlin
hydrogen
perverted
graveside
aiello
retake
wingspan
anatomy
instigated
astray
corazon
mikael
programmed
sturdy
confiscating
macedonia
dios
pissed
forgetful
sadism
maddening
plying
stares
enya
kelp
keepers
unlikeliest
luganda
cluttered
gianforte
crawling
bilal
pal
vicks
discerning
capone
ansari
discouragement
tomás
nurseries
respectable
hormones
mcgarvey
continetti
tantaros
exploitable
eloping
waad
warfare
pollster
gulen
towered
dialect
ger
krishnendu
mealtime
chew
lethality
yells
brainwashed
contrasted
ney
licit
yonsei
blacked
mildred
confuses
jurors
darwish
woodworker
eman
coronavirus
waggoner

poet
locomotive
fiesta
admirer
1875
unpack
redecorate
skyring
precepts
compulsive
coastlines
primitive
demonize
sitcom
coatings
suicides
copacabana
cso
kiir
aquifer
gunmen
algorithmic
breadfruit
butcher
glimpsed
bask
socioeconomics
gearhart
souring
musicals
crapser
collide
procreating
wiry
synagogue
lexi
flamed
denizens
sonic
cassy
ayurveda
tapes
mariam
emulating
kindling
conundrums
intergenerational
protruding
shoplifters
exhausts
sher
abuser
mustafa
dynamite
hyperventilation
writings
sledgehammers
animus
penciling
placards
saline
placeholder
damn
moon
treatable
meteorite
purposeful
1931
overconfidence
guffaw
collegiate
plural
flossing
achingly
artifacts
handprint
unmoving
alcott
449
embellishing
comedians
instrumentation
fop
braga
philharmonic
circumscribed
buttocks
admirably
lamb
suffocation
sunglasses
ti
abba
anagram
lawfare
ludicrous
sheba
oreos
resurrection
sunnis
stillhart
dominik
caldara
barter
loach
granick
rodents
siriusxm
forays
rashid
unblackening
unseat
pamphlets
rolando
v

In [ ]:
# Grab the highest probability words per topic

In [ ]:
for i topic in enumerate(LDA.components_):
    print(f"THE TOP 15 WORDS FOR TOPIC #{i}")
    print([cv.get_feature_names()[index]for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

In [ ]:
dtm

In [ ]:
npr

In [ ]:
topic_results = LDA.transform()

In [ ]:
topic_results[0].argmax()

In [ ]:
npr['Topic'] = topic_results.argmax(axis=1)

In [ ]:
npr